services:
  database:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 3306
    ports:
      - 127.0.0.1:3306:3306
  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ../backend:/var/www/tech
    expose:
      - 9000
    ports: 
      - 127.0.0.1:9000:9000
    links:
      - database
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - 127.0.0.1:80:80
    links:
      - node
      - database
      - php
  node:
    build:
      context: ./node
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ../frontend:/app
    expose:
      - 4200
    links:
      - php
